// Job ID: 6n9f73zosx77
cart={};function AddToCart(item,label,price,image,stock){if(cart[item]){if(cart[item].quantity<stock){cart[item].quantity+=1;}else{Inform("Item quantity exceeds stock limit");return;}}else{cart[item]={item:item,label:label,price:price,quantity:1,image:image,stock:stock};}let cur=parseInt($("#cart-index").text());$("#cart-index").text(`${cur+1}`);total=cur+1;$("#cart-index").show();}function UpdateCartItemQuantity(item,newQuantity){if(cart[item]){const stock=cart[item].stock;if(newQuantity>=1&&newQuantity<=stock){cart[item].quantity=newQuantity;}else if(newQuantity<1){Inform("Quantity should be at least 1");}else if(newQuantity>stock){Inform("Item quantity exceeds stock limit");}}else{Inform("Item not found in the cart");}}function updateTotalValues(){totalprice=0;total=0;for(let item in cart){const {price,quantity}=cart[item];let subtotal=price*quantity;totalprice+=subtotal;total+=quantity;}$(".checkout-panel-subtotal").text(`Total Due: $${totalprice}`);$(".checkout-panel-total").text(`Total Items: ${total}`);}function stepper(item,btn,action){let input=btn.parentElement.querySelector("input");let min=parseFloat(input.getAttribute("min"));let max=parseFloat(input.getAttribute("max"));let step=parseFloat(input.getAttribute("step"));let val=parseFloat(input.getAttribute("value"));let calcStep=(action==="increment")?step:-step;let newValue=val+calcStep;if(newValue<=0){delete cart[item];let cur=parseInt($("#cart-index").text());$("#cart-index").text(`${cur-1}`);total=cur-1;DisplayCart()}else if(newValue>=min&&newValue<=max){input.setAttribute("value",newValue);UpdateCartItemQuantity(item,newValue);updateTotalValues();}}function DisplayCart(){var Checkout=document.querySelector(".checkout-items");Checkout.innerHTML="";totalprice=0;if(Object.keys(cart).length===0){$("#panels").hide();$("#panels-nothing").show();cur=null;total=null;$("#cart-index").text("0");$("#cart-index").hide();}else{$("#panels-nothing").hide();for(let item in cart){let {label,price,quantity,image,stock}=cart[item];var div=document.createElement("div");div.className="checkout-item "+cart[item];let subtotal=price*quantity;totalprice+=subtotal;$(".checkout-panel-subtotal").text(`Total Due: $${totalprice}`);$(".checkout-panel-total").text(`Total Items: ${total}`);div.innerHTML=`
                <div class="container">
                    <button id="decrement"> - </button>
                    <input type="number" min="0" max="${stock}" step="1" value="${quantity}" readonly>
                    <button id="increment"> + </button>
                </div>

                <img class="checkout-item-image" src="${image}">
                <text class="checkout-item-name">${label}</text>
                <text class="checkout-item-price">$${price}</text>
            `;Checkout.appendChild(div);const decrementButton=div.querySelector('#decrement');const incrementButton=div.querySelector('#increment');decrementButton.addEventListener('click',()=>stepper(item,decrementButton,"decrement"));incrementButton.addEventListener('click',()=>stepper(item,incrementButton,"increment"));$("#panels").show();}}$("#cash").click(function(){$.post(`https://${GetParentResourceName()}/purchase`,JSON.stringify({type:"cash",cart:cart}));cur=null;total=null;cart={};$("#cart-index").text("0");$("#cart-index").hide();$("#checkout").hide();$("#items").show();$("#back").hide();});$("#card").click(function(){$.post(`https://${GetParentResourceName()}/purchase`,JSON.stringify({type:"bank",cart:cart}));cur=null;total=null;cart={};$("#cart-index").text("0");$("#cart-index").hide();$("#checkout").hide();$("#items").show();$("#back").hide();});}